name: policy-exception-check
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate exception file
        run: |
          set -e
          if [ -f .policy-exceptions/signed-images.json ]; then
            jq -e '.exceptions[] | select((.expires | fromdateiso8601) > (now))' .policy-exceptions/signed-images.json >/dev/null || { echo "Policy exception expired"; exit 1; }
            echo "Active exception found; proceed"
          else
            echo "No exception file"
          fi
