skip-paths:
  - evidence/**
  - artifacts/**
  - policy-exceptions/**
  - docs/**
external-modules-download-path: .external_modules
framework: all
quiet: true
soft-fail: false
severities: ["HIGH","CRITICAL"]
