site_name: AI Powered Infrastructure as a Product
site_url: https://saabolimpactventure.github.io/ai-powered-infrastructure-as-a-product/
repo_url: https://github.com/SAABOLImpactVenture/ai-powered-infrastructure-as-a-product
repo_name: SAABOLImpactVenture/ai-powered-infrastructure-as-a-product

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
