openapi: 3.0.3
info:
  title: Policy Evidence Adapter
  version: 1.0.0
paths:
  /aggregate:
    post:
      summary: Aggregate evidence counts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                kind: { type: string }
                status: { type: string }
                days: { type: integer, default: 30 }
      responses:
        "200":
          description: Aggregated counts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    status: { type: string }
                    kind: { type: string }
                    count: { type: integer }
