blank_issues_enabled: false
contact_links:
  - name: Questions / usage
    url: https://github.com/SAABOLImpactVenture/ai-powered-infrastructure-as-a-product/discussions
    about: Ask questions and get help in Discussions
