version: "3.9"
services:
  mcp:
    build: ./containers/mcp
    ports: ["127.0.0.1:8080:8080"]
    deploy:
      resources:
        limits: { cpus: "0.50", memory: "512M" }
    environment:
      - DEV_ONLY_BANNER=1
  policy-dashboard:
    build: ./services/policy-dashboard
    ports: ["127.0.0.1:8090:8090"]
    deploy:
      resources:
        limits: { cpus: "0.50", memory: "512M" }
    environment:
      - DEV_ONLY_BANNER=1
