version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.108.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../observability/otel/collector.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
