name: plan-policy-apply
description: Secure plan -> policy -> apply with signed requests
inputs:
  mcp-url: { required: true, type: string }
  policy-url: { required: true, type: string }
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -e
        TOKEN="${{ github.token }}"
        curl -fsS -H "Authorization: Bearer $TOKEN" "${{ inputs.policy-url }}/health"
        curl -fsS -H "Authorization: Bearer $TOKEN" -X POST "${{ inputs.policy-url }}/evaluate" -d @tfplan.json
        curl -fsS -H "Authorization: Bearer $TOKEN" -X POST "${{ inputs.mcp-url }}/apply" -d @tfplan.bin
