
name: sbom-attest
description: Build SPDX SBOM and cosign attest
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -e
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
        syft dir:. -o spdx-json > artifacts/sbom/repo.spdx.json
        echo "SBOM at artifacts/sbom/repo.spdx.json"
