apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: landing-zone-addon
  title: Landing Zone Add-On
  description: Scaffolds a repo/module to extend an existing landing zone with compliant settings.
spec:
  owner: group:default/platform-admins
  type: service
  parameters:
    - title: Add-on details
      required: [name, provider, environment, program]
      properties:
        name:
          type: string
          pattern: "^[a-z0-9-]+$"
        provider:
          type: string
          enum: [aws, azure, gcp, oci]
        environment:
          type: string
          enum: [Dev, Test, Prod]
          default: Prod
        program:
          type: string
          default: AI-PIaP
    - title: GitHub destination
      required: [repoUrl]
      properties:
        repoUrl:
          type: string
          ui:field: RepoUrlPicker
          ui:options: { allowedHosts: ["github.com"] }
  steps:
    - id: validate
      name: Validate Required Tags
      action: aipiap:validate:tags
      input:
        tags:
          Program: "{{ parameters.program }}"
          System: "{{ parameters.name }}"
          Environment: "{{ parameters.environment }}"
          "Data-Class": "Internal"
    - id: fetch
      action: fetch:template
      name: Fetch template
      input:
        url: ./skeleton
        values:
          name: "{{ parameters.name }}"
          provider: "{{ parameters.provider }}"
          environment: "{{ parameters.environment }}"
          program: "{{ parameters.program }}"
    - id: publish
      action: publish:github
      input:
        repoUrl: "{{ parameters.repoUrl }}"
        defaultBranch: main
        protectDefaultBranch: true
    - id: register
      action: catalog:register
      input:
        repoContentsUrl: "{{ steps.publish.output.repoContentsUrl }}"
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - title: Repository
        url: "{{ steps.publish.output.remoteUrl }}"
      - title: Open in catalog
        url: "{{ steps.register.output.catalogEntityUrl }}"
