#!/usr/bin/env bash
set -euo pipefail
#
# Resolve Azure Private Endpoint IP addresses for Postgres and Key Vault,
# then generate a Helm overlay file (charts/backstage/values-aks-overlay.prod.yaml)
# with exact /32 CIDRs for networkPolicy.egressAllowCIDRs.
#
# Inputs (env):
#   AZ_SUBSCRIPTION_ID   - Azure subscription
#   AZ_RESOURCE_GROUP    - Resource group containing the Private Endpoints
#   PG_PE_NAME           - Name of the Postgres Private Endpoint
#   KV_PE_NAME           - Name of the Key Vault Private Endpoint
#   PROXY_IPS            - (optional) comma-separated list of proxy IPs to allow (e.g., "10.50.0.10,10.50.0.11")
#   WORKLOAD_IDENTITY_CLIENT_ID - client ID for Workload Identity SA annotation
#
# Requires: az, yq (v4), jq
#
# Output:
#   charts/backstage/values-aks-overlay.prod.yaml
#

: "${AZ_SUBSCRIPTION_ID:?}"
: "${AZ_RESOURCE_GROUP:?}"
: "${PG_PE_NAME:?}"
: "${KV_PE_NAME:?}"
: "${WORKLOAD_IDENTITY_CLIENT_ID:?}"

az account set --subscription "${AZ_SUBSCRIPTION_ID}"

get_ips() {
  local name="$1"
  az network private-endpoint show -g "${AZ_RESOURCE_GROUP}" -n "${name}"     --query "networkInterfaces[].ipConfigurations[].privateIPAddress" -o tsv | tr '\n' ' ' | xargs -n1
}

PG_IPS=($(get_ips "${PG_PE_NAME}"))
KV_IPS=($(get_ips "${KV_PE_NAME}"))

CIDRS=()

if [ -n "${PROXY_IPS:-}" ]; then
  IFS=',' read -ra PIPS <<< "${PROXY_IPS}"
  for ip in "${PIPS[@]}"; do
    CIDRS+=("${ip}/32")
  done
fi

for ip in "${PG_IPS[@]}"; do CIDRS+=("${ip}/32"); done
for ip in "${KV_IPS[@]}"; do CIDRS+=("${ip}/32"); done

mkdir -p charts/backstage

cat > charts/backstage/values-aks-overlay.prod.yaml <<EOF
# Generated by scripts/aks/generate-aks-overlay.sh
namespace: backstage

serviceAccount:
  annotations:
    azure.workload.identity/client-id: "${WORKLOAD_IDENTITY_CLIENT_ID}"

ingress:
  enabled: true
  className: "private"
  tls:
    enabled: true
    secretName: backstage-tls
  backend:
    enabled: true
    host: backstage-api.internal.example.gov
  app:
    enabled: true
    host: backstage.internal.example.gov

backend:
  extraEnv:
    NODE_EXTRA_CA_CERTS: /etc/mtls/ca.crt
    PGSSLMODE: verify-full
    PGSSLCERT: /etc/mtls/client.crt
    PGSSLKEY: /etc/mtls/client.key
    PGSSLROOTCERT: /etc/mtls/ca.crt
    HTTPS_PROXY: \${HTTPS_PROXY:-}
    HTTP_PROXY: \${HTTP_PROXY:-}
    NO_PROXY: "localhost,127.0.0.1,.svc,.cluster.local"
  volumeMounts:
    - name: mtls
      mountPath: /etc/mtls
      readOnly: true
  volumes:
    - name: mtls
      secret:
        secretName: backstage-mtls

app:
  volumeMounts:
    - name: mtls
      mountPath: /etc/mtls
      readOnly: true
  volumes:
    - name: mtls
      secret:
        secretName: backstage-mtls

networkPolicy:
  enabled: true
  egressAllowCIDRs:
$(for c in "${CIDRS[@]}"; do echo "    - "${c}""; done)
EOF

echo "Wrote charts/backstage/values-aks-overlay.prod.yaml with CIDRs:"
printf ' - %s
' "${CIDRS[@]}"
