name: apply-azure

on:
  workflow_dispatch:
    inputs:
      tf-root:
        description: "Path to Terraform root to apply (e.g. products/azure/example)"
        required: true
      approve:
        description: "Type 'apply' to confirm"
        required: true

permissions:
  id-token: write
  contents: read

env:
  ARM_USE_OIDC: "true"
  TF_IN_AUTOMATION: "1"

jobs:
  apply:
    if: inputs.approve == 'apply'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_SUB_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Apply
        working-directory: ${{ inputs.tf-root }}
        env:
          ARM_USE_OIDC: "true"
        run: |
          terraform init -input=false -no-color
          terraform apply -auto-approve -input=false -no-color
