name: ci-bicep-validate

on:
  pull_request:
    branches: [ "**" ]
    paths:
      - "products/azure/**/*.bicep"
      - ".github/workflows/ci-bicep-validate.yml"

permissions:
  contents: read

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      azure_bicep: ${{ steps.changes.outputs.azure_bicep }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            azure_bicep:
              - 'products/azure/**/*.bicep'

  validate-bicep:
    runs-on: ubuntu-latest
    needs: detect
    if: needs.detect.outputs.azure_bicep == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Install Bicep CLI
        run: |
          az version || curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install
          az bicep version
      - name: Validate changed Bicep files
        run: |
          set -e
          mapfile -t FILES < <(git diff --name-only origin/${{ github.base_ref }}... | grep -E '\.bicep$' || true)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No *.bicep changes detected; exiting."
            exit 0
          fi
          for f in "${FILES[@]}"; do
            echo ">> az bicep build --file $f"
            az bicep build --file "$f"
          done
