name: ci-bicep-validate
on: [pull_request, workflow_dispatch]
permissions: { contents: read }
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/cli@v2
      - name: Pin & build Bicep
        run: |
          az bicep version
          az bicep upgrade --version 0.31.92
          az bicep build --file iac/azure/main.bicep
