name: ci-cloud
on: [pull_request, workflow_dispatch]
permissions: { contents: read, id-token: write }
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ 'platform/aws/networking', 'policies/aws/fedramp', 'evidence/immutable/aws' ]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.8.6 }
      - name: Validate (no backend)
        working-directory: ${{ matrix.module }}
        run: |
          terraform init -input=false -backend=false
          terraform validate -no-color
