name: ci-matrix
on: [pull_request, workflow_dispatch]
permissions: { contents: read, id-token: write, security-events: write }
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: [ 'workloads/product/sample-aws', 'workloads/product/sample-azure', 'workloads/product/sample-gcp' ]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.8.6 }
      - name: Init & Validate (no backend)
        working-directory: ${{ matrix.path }}
        run: |
          terraform init -input=false -backend=false
          terraform validate

  iac-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tflint (pinned)
        uses: terraform-linters/setup-tflint@v4
        with: { tflint_version: v0.53.0 }
      - name: Run tflint (fail on problems)
        run: |
          tflint --init
          tflint -f compact
      - name: Checkov (TF/K8s/Helm) — SARIF
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: false
          framework: terraform,kubernetes,helm
          output_format: sarif
          output_file_path: checkov.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: checkov.sarif }
      - name: Conftest (OPA)
        run: conftest test --policy policy/ .
