name: ci-matrix
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - platform/azure/observability/log_analytics
          - workloads/iaap/modules/aws/networking
          - platform/gcp/audit/log_sink
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.8.6 }
      - name: Init & Validate (no backend)
        working-directory: ${{ matrix.path }}
        run: |
          terraform init -input=false -backend=false
          terraform validate -no-color

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install tools
        run: pip install ruff bandit
      - name: Ruff + Bandit
        run: |
          ruff check .
          bandit -q -r scripts -x "*/__pycache__/*"

  tflint-checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tflint (pinned)
        uses: terraform-linters/setup-tflint@v4
        with: { tflint_version: v0.53.0 }
      - name: Run tflint (fail on problems)
        run: |
          tflint --init
          tflint -f compact
      - name: Checkov (terraform only)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: false
          framework: terraform
