name: Pre-commit (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: "-a"
