name: ci-security
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  id-token: write
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  iac-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v4
        with: { tflint_version: v0.53.0 }
      - name: Run tflint (fail on problems)
        run: |
          tflint --init
          tflint -f compact
      - name: Checkov (TF/K8s/Helm) SARIF
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: false
          framework: terraform,kubernetes,helm
          output_format: sarif
          output_file_path: checkov.sarif
      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: checkov.sarif }
      - name: Conftest gate (OPA)
        run: conftest test --policy policy/ .
