name: e2e-suite
on: [workflow_dispatch]
permissions: { contents: read, id-token: write }
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  run-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq (pinned + checksum)
        run: |
          set -e
          VER=v4.44.3
          curl -sSLo yq.tar.gz https://github.com/mikefarah/yq/releases/download/${VER}/yq_linux_amd64.tar.gz
          echo "SHA256SUM  yq.tar.gz" > yq.sha256
          # TODO: replace SHA256SUM with real checksum from release
          sha256sum -c yq.sha256 || (echo "Checksum mismatch" && exit 1)
          tar -xzf yq.tar.gz
          sudo mv yq_linux_amd64 /usr/local/bin/yq
      - name: Build compose (with healthchecks)
        run: |
          docker compose -f docker-compose.yml up -d --build
          for s in mcp policy-dashboard; do
            echo "Waiting for $s..."; n=0; until [ $n -ge 30 ]; do docker inspect --format='{{json .State.Health.Status}}' $(docker compose ps -q $s) 2>/dev/null | grep -q healthy && break; n=$((n+1)); sleep 5; done
          done
