name: example-oidc-azure
on: [pull_request, workflow_dispatch]
permissions: { contents: read, id-token: write }
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-log-analytics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.8.6 }
      - name: Terraform validate (Log Analytics module, no backend)
        working-directory: iac/azure/log-analytics
        run: |
          terraform init -backend=false -input=false
          terraform validate
