name: oscal-check
on:
  workflow_dispatch:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check OSCAL artifact
        run: |
          test -f artifacts/oscal/assessment-results.json || (echo "Missing OSCAL assessment-results.json" && exit 1)
          jq -e '.["assessment-results"]' artifacts/oscal/assessment-results.json >/dev/null || (echo "Invalid OSCAL structure" && exit 1)
