name: terraform plan (azure)

on:
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/plan-azure.yml"
      - ".github/workflows/terraform-reusable.yml"
      - "products/azure/example/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      tf_path: "products/azure/example"
      azure_subscription: ${{ secrets.PLATFORM_SUB_ID }}
      state_rg: ${{ vars.STATE_RG }}
      state_sa: ${{ vars.STATE_SA }}
      state_container: ${{ vars.STATE_CT }}
      state_key: "products-azure-example.tfstate"
      do_apply: false
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_OIDC_CLIENT_ID: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
