name: plan-policy-azure
on:
  pull_request:
    paths: ['products/azure/**', 'policies/**']
permissions:
  id-token: write
  contents: read
  security-events: write
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_SUB_ID }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init/Plan (JSON)
        env:
          ARM_USE_AZUREAD: true
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.PLATFORM_SUB_ID }}
        run: |
          terraform -chdir=products/azure/example init             -backend-config="storage_account_name=${{ secrets.STATE_STORAGE_ACCOUNT }}"             -backend-config="container_name=${{ secrets.STATE_CONTAINER }}"
          terraform -chdir=products/azure/example plan -out=tfplan
          terraform -chdir=products/azure/example show -json tfplan > plan.json
      - uses: actions/upload-artifact@v4
        with: { name: tf-plan, path: plan.json }

  policy:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: tf-plan }
      - name: tfsec
        run: tfsec --format sarif --out tfsec.sarif .
      - name: checkov (plan.json)
        run: checkov -o sarif -f plan.json > checkov.sarif
      - name: conftest
        run: conftest test --policy policies/ plan.json
      - name: Upload SARIF (merged)
        run: jq -s '{version:"2.1.0", runs:(.[0].runs + .[1].runs)}' tfsec.sarif checkov.sarif > merged.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: merged.sarif }
