
name: policy-gcp
on:
  workflow_dispatch:
    inputs:
      project_id:
        description: GCP Project ID
        required: true
jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform apply GCP org policies
        working-directory: policies/gcp/org-policy
        env:
          TF_VAR_project_id: ${{ inputs.project_id }}
        run: |
          terraform init -backend=false
          terraform apply -auto-approve
