name: policy-baselines-enforce
on:
  workflow_dispatch:
  pull_request:
permissions: { contents: read }
jobs:
  azure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Query Azure Policy states
        run: |
          az policy state summarize --top 5 | tee azure-policy.json
          jq -e '.results[0].nonCompliantResources==0' azure-policy.json
  aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with: { role-to-assume: ${{ secrets.AWS_ROLE_ARN }}, aws-region: ${{ secrets.AWS_REGION }} }
      - name: Check AWS Config rule
        run: |
          aws configservice describe-compliance-by-config-rule --config-rule-names s3-bucket-public-read-prohibited | tee aws-config.json
          jq -e '.ComplianceByConfigRules[0].Compliance.ComplianceType=="COMPLIANT"' aws-config.json
  gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with: { workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}, service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }} }
      - name: Verify Org Policy
        run: |
          gcloud beta resource-manager org-policies describe sql.restrictPublicIp --project="$GCP_PROJECT" | tee gcp-policy.txt
          grep -q "inheritFromParent: false" gcp-policy.txt
