name: policy-k8s
on: [workflow_dispatch]
permissions: { contents: read, id-token: write }
concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  apply-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AKS context via OIDC (example)
        uses: azure/aks-set-context@v4
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name: ${{ secrets.AKS_NAME }}
      - name: Apply policies with retry
        run: |
          set -e
          n=0
          until [ $n -ge 5 ]; do
            kubectl apply -f k8s/policy && break
            n=$((n+1)); sleep 5
          done
      - name: Wait for admission controllers
        run: kubectl wait --for=condition=Available -n gatekeeper-system deployment/gatekeeper-controller-manager --timeout=120s
