name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate changelog (simple)
        id: notes
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "Release $GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          git log -1 --pretty=format:"%h %s" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.CHANGELOG }}
