name: secret-scan
on: [pull_request, workflow_dispatch]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
