name: slsa-provenance
on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read
jobs:
  build-provenance:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: mcp-azure,       dockerfile: servers/mcp/azure/Dockerfile.distroless,       context: . }
          - { name: mcp-policy-azure, dockerfile: servers/mcp-policy/azure/Dockerfile.distroless, context: . }
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.name }}-latest
          platforms: linux/amd64,linux/arm64
      - name: Generate provenance
        uses: slsa-framework/slsa-github-generator/actions/delegator@v2.0.0
        with:
          build-artifact-path: ""
          compile-generator: true
          upload-assets: true
